### ISSUE TITLE
Duplicated IF statetment 

### ISSUE THREAD

**Issue by daguitosama** [tom-sherman/tom-sherman.com#32]
Hey i have been browsing this source to learn how to do stuff with Remix and Cloudflare, found this duplicated [`if`](https://github.com/tom-sherman/tom-sherman.com/blob/8beae3b36912eb82615f3a14bc65614895834553/functions/api/blog-webhook.ts#LL25C3-L25C3) thinked you might want to know about. Thanks for building this on public, is a nice example on how to wire up things. There is a SQL database going on here ?

**Comment by tom-sherman** [comment]
Good spot, thanks! Fixed now 😄 

> There is a SQL database going on here ?

Yup, it uses Cloudflare D1 which is currently in open alpha: https://blog.cloudflare.com/introducing-d1/
